import { defineCollection } from 'astro:content';
import { glob } from 'astro/loaders';
import { z } from 'zod';

const homepage = defineCollection({
  loader: glob({ base: './src/content/homepage', pattern: '**/*.json' }),
  schema: z.object({
    title: z.string(),
    description: z.string(),
    publicationTitle: z.string(),
    authors: z.string(),
    affiliation1: z.string(),
    affiliation2: z.string(),
    email: z.string(),
    arxiv: z.string(),
    code: z.string(),
    reproduction: z.string(),
    fig1Caption: z.string(),
    abstractTitle: z.string(),
    abstractP1: z.string(),
    abstractP2: z.string(),
    abstractP3: z.string(),
    abstractP4: z.string(),
    challengesTitle: z.string(),
    challengesDesc: z.string(),
    fig2Caption: z.string(),
    bibtexTitle: z.string(),
    copy: z.string(),
    copied: z.string(),
    resourcesTitle: z.string(),
    cvfPaper: z.string(),
    poster: z.string(),
    todoTitle: z.string(),
    todo1: z.string(),
    todo2: z.string(),
  }),
});

const reprod = defineCollection({
  loader: glob({ base: './src/content/reprod', pattern: '**/*.json' }),
  schema: z.object({
    title: z.string(),
    pageTitle: z.string(),
    subtitle: z.string(),
    backHome: z.string(),
    envTitle: z.string(),
    cleanTitle: z.string(),
    cleanP1: z.string(),
    cleanConda: z.string(),
    cleanVenv: z.string(),
    cleanNote: z.string(),
    installUvTitle: z.string(),
    installUvDesc: z.string(),
    installUvNoNet: z.string(),
    installUvUpgrade: z.string(),
    installUvVerify: z.string(),
    installUvBaseline: z.string(),
    troubleshootingTitle: z.string(),
    troubleshootingAfterInstall: z.string(),
    getCodeTitle: z.string(),
    getCodeDesc: z.string(),
    getCodeEnter: z.string(),
    getCodeStructure: z.string(),
    initTitle: z.string(),
    initDesc: z.string(),
    initNote: z.string(),
    envSelfCheck: z.string(),
    versionConstraints: z.string(),
    activateTitle: z.string(),
    activateNote: z.string(),
    activateVerify: z.string(),
    activateExample: z.string(),
    dataTitle: z.string(),
    dataDesc: z.string(),
    datasetDownload: z.string(),
    processedData: z.string(),
    rawData: z.string(),
    trainingTitle: z.string(),
    trainingModelTitle: z.string(),
    trainingConfig: z.string(),
    trainingConfigDesc: z.string(),
    trainingHyper: z.string(),
    trainingHyperDesc: z.string(),
    trainingExec: z.string(),
    trainingExecPerm: z.string(),
    trainingExecStart: z.string(),
    outputsTitle: z.string(),
    outputsDesc: z.string(),
    wandbTitle: z.string(),
    wandbDesc: z.string(),
    wandbLogPath: z.string(),
    wandbRunDir: z.string(),
    wandbUpload: z.string(),
    wandbUploadDesc: z.string(),
    footerNote: z.string(),
  }),
});

const tool = defineCollection({
  loader: glob({ base: './src/content/tool', pattern: '**/*.json' }),
  schema: z.object({
    title: z.string(),
    tab1: z.string(),
    tab2: z.string(),
    modelSize: z.string(),
    trainingTokens: z.string(),
    calculate: z.string(),
    results: z.string(),
    optimalBs: z.string(),
    lr: z.string(),
    modelType: z.string(),
    moe: z.string(),
    dense: z.string(),
    na: z.string(),
    show: z.string(),
    placeholder: z.string(),
  }),
});

const footer = defineCollection({
  loader: glob({ base: './src/content/footer', pattern: '**/*.json' }),
  schema: z.object({
    templateFrom: z.string(),
    licensedUnder: z.string(),
  }),
});

export const collections = { homepage, reprod, tool, footer };
